/* 
 * Author: Kim Min-Ho (ISKU)
 * Date: 2016.07.15
 * email: minho1a@hanmail.net
 * 
 * https://github.com/ISKU/Algorithm
 * https://www.acmicpc.net/problem/2816
 */

import java.util.Scanner;

public class Main {
	public static void main(String args[]) {

		Scanner input = new Scanner(System.in);
		StringBuilder sequenceOfAnyOperations = new StringBuilder();
		int indexOfFirstChannel = 1, indexOfSecondChannel = 2;
		int numberOfChannels = input.nextInt(); // number of channels.
		String[] channelList = new String[numberOfChannels]; // channel list.

		// Next N lines contain a list of channels generated by the digital receiver.
		for (int index = 0; index < numberOfChannels; index++) {
			String tempChannel = input.next(); // input, channels.

			// KBS1 will be on the first, and KBS2 on the second place in channel list.
			if (tempChannel.equals("KBS1"))
				indexOfFirstChannel = index;
			if (tempChannel.equals("KBS2"))
				indexOfSecondChannel = index;

			channelList[index] = tempChannel;
		}

		// When KBS2 is in the below KBS1, KBS2 goes down one line in the channel list.
		if (indexOfSecondChannel < indexOfFirstChannel)
			indexOfSecondChannel++;

		// Moves the KBS1.
		for (int arrow = 0; arrow < indexOfFirstChannel; arrow++)
			sequenceOfAnyOperations.append("1");
		for (int arrow = 0; arrow < indexOfFirstChannel; arrow++)
			sequenceOfAnyOperations.append("4");

		// Moves the KBS2.
		for (int arrow = 0; arrow < indexOfSecondChannel; arrow++)
			sequenceOfAnyOperations.append("1");
		for (int arrow = 0; arrow < indexOfSecondChannel - 1; arrow++)
			sequenceOfAnyOperations.append("4");

		System.out.println(sequenceOfAnyOperations); // output, sequence of commands with no spaces in between.
	}
}